### register user (not confirmed) (all)
POST http://localhost:52731/api/signUp
Content-Type: application/json

{
  "name" : "name",
  "email" : "user@mail.ru",
  "password" : "qwerty228"
}

### login and get token (all)

POST http://localhost:52825/api/login
Content-Type: application/json

{
  "email": "user@mail.ru",
  "password": "qwerty228"
}
### check token and health (ADMIN)

GET http://localhost:52825/actuator/health
Authorization: Bearer 0d2698c0-fe7f-48f4-acc7-92d3cf3241cf
