spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath:init/schema.sql
    data: classpath:init/data.sql
  jpa:
    hibernate:
      ddl-auto: none
