spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/medical}
    username: ${POSTGRES_DB_USERNAME:postgres}
    password: ${POSTGRES_DB_PASSWORD:12212332}
    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
#    schema: classpath:init/schema.sql
#    data: classpath:init/data.sql
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: ${LIQUIBASE_ENABLE:false}


